name: M3U generator

on:
  schedule:
    - cron: '0 0/3 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Delete log
        run: |
          rm -rf ./log.txt

      - name: Install CA Certificate
        run: |
          sudo apt-get install -y ca-certificates
          sudo curl -o /usr/local/share/ca-certificates/cacert.pem https://curl.se/ca/cacert.pem
          sudo update-ca-certificates

      - name: Main
        run: |
          pwd
          chmod +x generate.sh
          ./generate.sh

      - name: git pull
        run: |
          git pull origin main

      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit & push
        run: |
          git commit -m "links are updated"
          git push
